name: Secure CI Pipeline for auth Service

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
  security-events: write

jobs:
  ci-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{ vars.JF_URL }}
          IMAGE_NAME: tompazus.jfrog.io/tomp-docker-dev-local/auth:${{ github.run_number }}
        with:
          oidc-provider-name: github-jfrog-cli
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_URL }}
          username: ${{ steps.setup-cli.outputs.oidc-user }}
          password: ${{ steps.setup-cli.outputs.oidc-token }}
      
      - name: Set IMAGE_NAME env var
        run: echo "IMAGE_NAME=tompazus.jfrog.io/tomp-docker-dev-local/auth:${{ github.run_number }}" >> $GITHUB_ENV

      
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: configure jfrog environment
        run: |
          jf pip-config --repo-resolve=python-virtual    

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          jf pip install -r auth/requirements.txt --module=auth-python-deps
          # pip install --no-cache-dir -r auth/requirements.txt

      - name: Run Unit Tests
        run: pytest auth/test_server.py
      
      # - name: Frogbot by JFrog  # 🔹 Add Frogbot Scan in CI
      #   uses: jfrog/frogbot@v2.25.0
      #   env:
      #     JF_URL: ${{ vars.JF_URL }}
      #     JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      #     JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}  # ✅ Fix: Add missing GitHub token

      # - name: Authenticate with JFrog Artifactory
      #   run: |
      #     echo "${{ secrets.JF_ACCESS_TOKEN }}" | docker login tompazus.jfrog.io --username "${{ secrets.JF_USER }}" --password-stdin

      
      - name: Install Hadolint
        run: |
          curl -sSL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint

      - name: Lint Dockerfile for Security Best Practices
        run: hadolint auth/Dockerfile
      
      - name: build Docker Image Before Scanning
        run: |
          echo "Building image: $IMAGE_NAME"
          docker build --build-arg PIP_INDEX_URL="https://${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}@tompazus.jfrog.io/artifactory/api/pypi/python-virtual/simple" --build-arg DEBIAN_REMOTE_URL="https://${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}@tompazus.jfrog.io/artifactory/debian-remote" -t $IMAGE_NAME ./auth

      # - name: Install Syft for SBOM Generation
      #   run: |
      #     curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      # - name: Generate SBOM (Software Bill of Materials)
      #   run: |
      #     syft $IMAGE_NAME -o json > sbom.json
      #     cat sbom.json
      
      # - name: Upload SBOM as an Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sbom
      #     path: sbom.json

      - name: Run XRay Scan Locally
        run: jf docker scan $IMAGE_NAME --output json > xray-scan-results.json
      
      - name: Upload XRay Scan Results as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xray-scan-results
          path: xray-scan-results.json

      # - name: Fail if Critical Vulnerabilities Exist
      #   run: |
      #     if grep -q '"severity": "Critical"' xray-scan-results.json; then
      #       echo "❌ Critical vulnerabilities found! Failing build..."
      #       exit 1
      #     fi
      #     echo "✅ No critical vulnerabilities found."

      - name: Enable Docker BuildKit & Secure Buildx
        run: |
          export DOCKER_BUILDKIT=1
          docker buildx create --use

      - name: Build & Push Multi-Arch Secure Docker Image
        env:
          JFROG_CLI_BUILD_NAME: auth-build
          JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          jf docker buildx build --platform linux/amd64 \
            --build-arg PIP_INDEX_URL="https://${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}@tompazus.jfrog.io/artifactory/api/pypi/python-virtual/simple" \
            --build-arg DEBIAN_REMOTE_URL="https://${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}@tompazus.jfrog.io/artifactory/debian-remote" \
            --tag $IMAGE_NAME \
            --file auth/Dockerfile \
            --metadata-file=build-metadata \
            --push \
            auth/
          cat build-metadata
      - name: Extract Digest using Buildx Imagetools
        run: |
          REF=$(docker buildx imagetools inspect $IMAGE_NAME --format '{{ (index .Manifest.Manifests 0).Digest }}')
          FULL_REF="${IMAGE_NAME%@*}@$REF"
          echo "$FULL_REF" > image.txt
          echo "✅ Final image reference:"
          cat image.txt
          jf rt build-docker-create tomp-docker-dev-local --image-file image.txt --build-name auth-build --build-number ${{ github.run_number }}
          jf rt build-collect-env auth-build ${{ github.run_number }}
          jf rt build-add-git auth-build ${{ github.run_number }}
          jf rt build-publish auth-build ${{ github.run_number }}
          
      - name: Install Cosign v2.5.3
        run: |
          COSIGN_VERSION="v2.5.3"
          curl -Lo cosign "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64"
          chmod +x cosign
          sudo mv cosign /usr/local/bin/cosign
          cosign version
      - name: Sign Docker Image with Cosign
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign version
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          chmod 600 cosign.key  # Secure key permissions
          cosign sign --key cosign.key --upload=true $IMAGE_NAME -y

      # - name: Publish Build Info with JFrog CLI
      #   env:
      #     JFROG_CLI_BUILD_NAME: auth-build
      #     JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
      #   run: |
      #     jf rt build-collect-env
      #     jf rt build-add-git
      #     jf rt build-publish
      #     digest=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME | cut -d@ -f2)
      #     echo "$IMAGE_NAME@$digest" > image.txt
      #     jf rt build-docker-create tomp-docker-dev-local --image-file image.txt --build-name auth-build --build-number ${{ github.run_number }}
      
      - name: Run XRay Vulnerability Scan and Attach to Build
        run: |
          jf build-scan auth-build ${{ github.run_number }}